### ISSUE TITLE
typo changing remote

### ISSUE THREAD

**Issue by PeterNerlich** [7HAL32/robolab-template#1]
`git remote set-URL origin https://bitbucket.org/robolab-<season>-<year>/group-<id>` throws `error: Unknown subcommand: set-URL`
The command should be: `git remote set-url origin https://bitbucket.org/robolab-<season>-<year>/group-<id>`

**Comment by lutzthies** [comment]
Thanks for the report. This repository should not be used until tomorrow morning, as last bugfixes are coming in. I'll fix the typo in the next commit and will take the repository private again for a few hours.
